services:
  postgres:
    image: postgres:latest
    container_name: tasks_postgres_db
    environment:
      POSTGRES_USER: kris
      POSTGRES_PASSWORD: kris
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: